import React from 'react';
import { Prediction } from '../../types/prediction';
import { Target, Clock, ShieldAlert, Sparkles, AlertCircle } from 'lucide-react';

interface PredictionCardProps {
  prediction: Prediction;
}

export const PredictionCard: React.FC<PredictionCardProps> = ({ prediction }) => {
  return (
    <div className="bg-gradient-to-b from-[#0A182E] to-[#071120] border border-cyan-500/30 rounded-xl p-4 shadow-xl relative overflow-hidden">
      {/* Tactical Glow Effect */}
      <div className="absolute top-0 right-0 w-36 h-36 bg-cyan-500/10 rounded-full blur-2xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between pb-2 mb-3 border-b border-white/[0.08]">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-cyan-400" />
          <h3 className="font-mono text-xs font-bold text-cyan-300 uppercase tracking-wider">
            AI CASH-OUT PREDICTION
          </h3>
        </div>
        <span className="font-mono text-[10.5px] px-2 py-0.5 rounded bg-cyan-950/60 border border-cyan-500/30 text-cyan-300 font-semibold">
          Model Prediction
        </span>
      </div>

      {/* Primary Highlight Block */}
      <div className="flex items-center justify-between bg-[#030914] p-3.5 rounded-lg border border-cyan-500/20 mb-3">
        <div>
          <span className="text-[10.5px] font-mono text-slate-400 uppercase tracking-wider block">
            Predicted Extraction Zone
          </span>
          <div className="flex items-baseline gap-2 mt-0.5">
            <span className="text-2xl font-display font-extrabold text-white tracking-wider">
              {prediction.predictedZone}
            </span>
            <span className="text-xs font-mono text-cyan-400 font-semibold">
              (North Goa Corridor)
            </span>
          </div>
        </div>

        <div className="text-right">
          <span className="text-[10.5px] font-mono text-slate-400 uppercase tracking-wider block">
            Model Confidence
          </span>
          <span className="text-2xl font-mono font-extrabold text-red-400">
            {prediction.confidencePercent}
          </span>
        </div>
      </div>

      {/* Estimated Withdrawal Window */}
      <div className="bg-[#030914] p-3 rounded-lg border border-white/[0.06] flex items-center justify-between text-xs">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
            <Clock className="w-4 h-4" />
          </div>
          <div>
            <span className="text-[10.5px] font-mono text-slate-400 uppercase block">
              Estimated Withdrawal Window
            </span>
            <span className="font-mono font-bold text-amber-300 text-sm">
              {prediction.timeWindow}
            </span>
          </div>
        </div>
        <div className="text-right">
          <span className="text-[10px] font-mono text-slate-400 uppercase block">Likelihood</span>
          <span className="font-mono text-xs font-bold text-amber-400">PEAK SYNDICATE</span>
        </div>
      </div>

      {/* Forensic Disclaimer */}
      <div className="mt-3 flex items-start gap-1.5 text-[10px] text-slate-400 leading-tight">
        <AlertCircle className="w-3 h-3 text-slate-500 shrink-0 mt-0.5" />
        <span>Generated by XGBoost geospatial model evaluating temporal cadence and ATM topology. Not legal certainty.</span>
      </div>
    </div>
  );
};
